# Pure preset - minimal prompt
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
style = "blue"

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[■](bold yellow)"

[git_branch]
format = "[$branch]($style) "
style = "bright-black"

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "magenta"
conflicted = "=$count "
untracked = "?$count "
modified = "!$count "
staged = "+$count "
renamed = "»$count "
deleted = "✘$count "
stashed = "≡$count "
ahead = "⇡$count "
behind = "⇣$count "
diverged = "⇕⇡$ahead_count⇣$behind_count "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
